title: "Satish Mane"
description: "Linux & DevOps — small tools, real fixes, no fluff."
url: "https://satishmane-sam.github.io"
baseurl: ""
lang: en

theme: minima
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title.html

author:
  name: Satish Mane

github_username: satishmane-sam

header_pages:
  - about.md

plugins:
  - jekyll-feed

exclude:
  - README.md
