title: "Satish Mane"
description: "Linux & DevOps — small tools, real fixes, no fluff."
url: "https://satishmane-sam.github.io"
baseurl: ""
lang: en

theme: minima
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title.html

author:
  name: Satish Mane
  email: satishmane-sam@users.noreply.github.com

github_username: satishmane-sam

header_pages:
  - about.md

minima:
  skin: auto
  social_links:
    github: satishmane-sam
    rss: atom

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
